kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-java-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Consuming-Apirest-Java-Deploy
  template:
    metadata:
      labels:
        app: Consuming-Apirest-Java-Deploy
    spec:
      containers:
        - name: my-java-springboot
          image: java-springboot-image:latest
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-java-springboot-svc
spec:
  ports:
    - name: http-8082
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: Consuming-Apirest-Java-Deploy