apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password